# @package _global_
defaults:
  - models: tcrp
  - datasets: etth1
  - trainers: tcrp_trainer
  - _self_

T:          336
H:          96
model_type: tcrp
include_gbm: false
checkpoint_dir: checkpoints
run_name: ''
seed: 42
